/**:
  ros__parameters:
    # Configuration file for SBG devices (HPI products) through a UDP interface.
    
    driver:
      # Node frequency (Hz)
      # Note: The frequency should be at least two times higher than the highest
      #       output frequency.
      #       The frequency can be reduced in order to reduce CPU consumption but
      #       it can lead to miss data frame and less accurate time stamping.
      frequency: 400

    odometry:
      # Enable/Disable ROS odometry messages.
      enable: false
      # Publish odometry transforms.
      publishTf: true
      # Odometry frame IDs.
      odomFrameId: "odom"
      baseFrameId: "base_link"
      initFrameId: "map"
    
    # Udp configuration
    ipConf:
      ipAddress: "0.0.0.0"              # Ip address of the device.
      out_port: 1234                    # Output port of the device.
      in_port: 5678                     # Inport of the device.    
   
    rtcm:
      # Should ros driver subscribe to RTCM topic
      subscribe: false
      # Topic on which RTCM is published
      topic_name: rtcm
      # Namespace where topic is published
      namespace: ntrip_client

    nmea:
      # Should ros driver publish NMEA string
      publish: false
      # Topic on which to publish nmea data
      topic_name: nmea
      # Namespace where to publish topic
      namespace: ntrip_client
